#!/bin/bash
# Start all service wrappers
# Generated by wrapper_generator.py

echo "Starting Get_Themas..."
nohup python3 /home/gomer/pythonCron/service_wrapper.py Get_Themas > /dev/null 2>&1 &
sleep 1

echo "Starting Clean_lock_files..."
nohup python3 /home/gomer/pythonCron/service_wrapper.py Clean_lock_files > /dev/null 2>&1 &
sleep 1

echo "Starting Converter..."
nohup python3 /home/gomer/pythonCron/service_wrapper.py Converter > /dev/null 2>&1 &
sleep 1

echo "Starting MySQL_Backup..."
nohup python3 /home/gomer/pythonCron/service_wrapper.py MySQL_Backup > /dev/null 2>&1 &
sleep 1

echo "Starting Check_Disk..."
nohup python3 /home/gomer/pythonCron/service_wrapper.py Check_Disk > /dev/null 2>&1 &
sleep 1

echo "Starting Copy_AB_files..."
nohup python3 /home/gomer/pythonCron/service_wrapper.py Copy_AB_files > /dev/null 2>&1 &
sleep 1

echo "Starting Backup_Zin_EAF_SRT_files..."
nohup python3 /home/gomer/pythonCron/service_wrapper.py Backup_Zin_EAF_SRT_files > /dev/null 2>&1 &
sleep 1

echo "Starting qRconvert..."
nohup python3 /home/gomer/pythonCron/service_wrapper.py qRconvert > /dev/null 2>&1 &
sleep 1

echo "Starting Move_StudioFiles..."
nohup python3 /home/gomer/pythonCron/service_wrapper.py Move_StudioFiles > /dev/null 2>&1 &
sleep 1

echo "Starting Check_if_raw_has_post_files..."
nohup python3 /home/gomer/pythonCron/service_wrapper.py Check_if_raw_has_post_files > /dev/null 2>&1 &
sleep 1

echo "Starting convert_zinString_to_LemmaList..."
nohup python3 /home/gomer/pythonCron/service_wrapper.py convert_zinString_to_LemmaList > /dev/null 2>&1 &
sleep 1

sleep 1

echo "Starting Update_field_gvg_at_sentences..."
nohup python3 /home/gomer/pythonCron/service_wrapper.py Update_field_gvg_at_sentences > /dev/null 2>&1 &
sleep 1

echo "Starting match_Records_for_LiveLink_videos_with_mocap_records..."
nohup python3 /home/gomer/pythonCron/service_wrapper.py match_Records_for_LiveLink_videos_with_mocap_records > /dev/null 2>&1 &
sleep 1

echo "Starting match_Vicon_FBX_CSV_files_with_mocap_records..."
nohup python3 /home/gomer/pythonCron/service_wrapper.py match_Vicon_FBX_CSV_files_with_mocap_records > /dev/null 2>&1 &
sleep 1

echo "Starting Convert_Livelink_videos..."
nohup python3 /home/gomer/pythonCron/service_wrapper.py Convert_Livelink_videos > /dev/null 2>&1 &
sleep 1

echo "All services started."
echo "Check status with: ps aux | grep service_wrapper.py"
